### ISSUE TITLE
OA系统是否有单独地方可以配置短信功能

### ISSUE THREAD

**Issue by dilenzhu** [o2oa/o2oa#100]
OA系统是否有单独地方可以配置短信功能，比如流程短信提醒，内容管理平台短信提醒呢？谢谢！

**Comment by o2oa** [comment]
可以的，可以通过config/message.json为指定的事件多准备一份消息，可以通过消息查询来处理消息接入到您需要的业务里，也可以将消息接入到Kafka或者activeMQ，由您自行完成消费。
您可以在www.o2oa.net的藕粉社区里提一个问题，管理员会回复您相应的方案。
