### ISSUE TITLE
办公中心处理代办事项，接口500异常咨询

### ISSUE THREAD

**Issue by handscmjunghee** [o2oa/o2oa#109]
# 背景
我在`https://www.o2oa.net/download.html`下载了`Linux-x64`版的安装包，已经配置好了mysql，并且已经成功启动。

# 问题
在`流程应用管理`中创建流程、在`办公中心`发起流程后后，需要进行操作的账号点击代办事项后接口返回错误信息：
```
{
  "type": "error",
  "message": "The Form object identified as :undefined does not exist.",
  "date": "2021-12-04 00:54:44",
  "spent": 16,
  "size": -1,
  "count": 0,
  "position": 0,
  "prompt": "com.x.base.core.project.exception.ExceptionEntityNotExist"
}
```
## 请求的接口是
`http://192.168.2.7:18080/x_processplatform_assemble_surface/jaxrs/form/v2/undefined?t=&v=6.3`
## Request
>GET /x_processplatform_assemble_surface/jaxrs/form/v2/undefined HTTP/1.1
Content-Type: application/json; charset=utf-8
Accept: text/html,application/json,*/*
Authorization: aNrqCdwh1n-RaeCEfaCVivK-pxeq2dHxHPJFFi3sWAVVxqN2FFb7JbrbfyMUFfLMW9XkO-K0F30
Accept-Encoding: gzip, deflate
Accept-Language: en-US
Host: 192.168.2.7:18080
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15
Connection: keep-alive
Referer: http://192.168.2.7:18080/x_desktop/index.html
Cookie: x-token=aNrqCdwh1n-RaeCEfaCVivK-pxeq2dHxHPJFFi3sWAVVxqN2FFb7JbrbfyMUFfLMW9XkO-K0F30; experimentation_subject_id=eyJfcmFpbHMiOnsibWVzc2FnZSI6IklqYzRNMlU0WVRWaExXUTRNalF0TkRKbU5DMDVaVGhqTFRRNFltWXhNbUU1WVRrek55ST0iLCJleHAiOm51bGwsInB1ciI6ImNvb2tpZS5leHBlcmltZW50YXRpb25fc3ViamVjdF9pZCJ9fQ%3D%3D--0e483a692f9a4e17fe8a337aa2f305933fede7f9
X-Requested-With: XMLHttpRequest
x-token: aNrqCdwh1n-RaeCEfaCVivK-pxeq2dHxHPJFFi3sWAVVxqN2FFb7JbrbfyMUFfLMW9XkO-K0F30

## Response
>HTTP/1.1 500 Server Error
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE, HEAD, TRACE
Access-Control-Expose-Headers: c-token, x-token
Access-Control-Max-Age: 86400
Set-Cookie: x-token=aNrqCdwh1n-RaeCEfaCVivK-pxeq2dHxHPJFFi3sWAVVxqN2FFb7JbrbfyMUFfLMW9XkO-K0F30; path=/; domain=192.168.2.7
Content-Type: application/json;charset=utf-8
Access-Control-Allow-Headers: x-requested-with, x-request, c-token, Content-Type, Content-Length, x-cipher, x-client, x-debugger, Authorization, P-User-Id, P-Request-Id, P-Page-Id, x-token
Content-Length: 260
Access-Control-Allow-Origin: *
x-token: aNrqCdwh1n-RaeCEfaCVivK-pxeq2dHxHPJFFi3sWAVVxqN2FFb7JbrbfyMUFfLMW9XkO-K0F30

## 

请问这是怎么回事呢？谢谢。

**Comment by handscmjunghee** [comment]
刚试了下，不使用mysql，把在`https://www.o2oa.net/download.html`下载的`Linux-x64`包直接运行起来也报同样的错误。

**Comment by o2oa** [comment]
从您的描述和报错上看，您是不是流程设计好之后，没有绑定表单？您可以先检查一下。

**Comment by handscmjunghee** [comment]
> 从您的描述和报错上看，您是不是流程设计好之后，没有绑定表单？您可以先检查一下。

感谢回复，创建流程后绑定表单，ok了，谢谢。
