### ISSUE TITLE
存储xss

### ISSUE THREAD

**Issue by wind226** [o2oa/o2oa#126]
发起流程申请：
![image](https://user-images.githubusercontent.com/24953996/165465533-65fb00b9-7bb1-4ab0-91f6-07b0d75c8afd.png)
填入以下信息：`'"><iMg SrC=x OnErRoR=alert(1)>{{7*7}}`
![image](https://user-images.githubusercontent.com/24953996/165465757-49e2aedd-e0ea-45c8-ae51-586dccd8949d.png)
转流的时候回触发一次
![image](https://user-images.githubusercontent.com/24953996/165465879-89843acf-699c-4c88-9204-f9c73ae7ebda.png)
转流意见填：`'"><iMg SrC=x OnErRoR=alert(8)>{{7*7}}`
![image](https://user-images.githubusercontent.com/24953996/165466116-2065dae9-ea99-4512-bf02-b14b5ef17a9c.png)
在流程待办里面触发xss：
![image](https://user-images.githubusercontent.com/24953996/165466387-907199d0-ca93-4994-8f2e-70f51541b6f9.png)

**Comment by caixiangyi** [comment]
您好，这个漏洞在7.2版本中已经修复
