### ISSUE TITLE
no Portal_?

### ISSUE THREAD

**Issue by justpic** [o2oa/o2oa#51]
没有Portal_这个类吗，还是没有开源

**Comment by o2oa** [comment]
当然有portal，是一个子项目，o2server/x_portal_**。

您找一下。

**Comment by bpmbank** [comment]
有idea环境下的开发部署文档吗，发现jpa还是配不起来，跑不了/

**Comment by o2oa** [comment]
idea应该是可以，o2Server是无法在IDE环境下跑的，需要编译打包成服务器，运行服务器。整套O2server源码打出来是一个包含5个服务器的Server。
带下划线的类，是编译源码的时候会编译出来的，您可以尝试一下整体编译。
