### ISSUE TITLE
除了系统使用教程, 在官网几乎找不到任何开发文档

### ISSUE THREAD

**Issue by Sohnny0** [o2oa/o2oa#53]
都不知道怎么在本地进行调试

**Comment by huqi1980** [comment]
o2oa.gitbook.io

**Comment by Sohnny0** [comment]
主要是没有代码模块的说明,  哪怕是基本的也行.  举个例子,我想增加一个后台接口,让前台用js调用,都不知道怎么操作...

**Comment by Sohnny0** [comment]
> https://o2oa.gitbook.io/

主要是没有代码模块的说明, 哪怕是基本的也行. 举个例子,我想增加一个后台接口,让前台用js调用,都不知道怎么操作...

**Comment by lovefox666** [comment]
其实号称免费开源的国内系统，是需要你们付费去请他们做技术支持的。

**Comment by zhouruicn** [comment]
完整教程请移步 https://www.yuque.com/o2oa
