### ISSUE TITLE
载入 store/jars 过程中无法找到文件:x_teamwork_core_entity.jar

### ISSUE THREAD

**Issue by raeuz** [o2oa/o2oa#79]
Hi,

参照 http://www.o2oa.net/course/ng5iqb.html 从源码编译 5.1.2 版本后,  执行 ./start_linux.sh 启动, 提示缺少文件:
`载入 store/jars 过程中无法找到文件:x_teamwork_core_entity.jar`.
但依然能够访问首页: 127.0.0.1:80

我看了个人目录, 倒是有个文件名类似的 `x_teamwork_core_entity-5.jar`

![image](https://user-images.githubusercontent.com/9192796/86744782-6e6f2480-c06c-11ea-9a48-6ae9476b245b.png)

**Comment by fancylou** [comment]
teamwork模块移出了默认应用列表，以后会以外部应用的方式添加
这个错误应该不影响其他功能使用

**Comment by raeuz** [comment]
了解.
谢谢.
