### ISSUE TITLE
在线体验效果很差，跟商用系统差距比较大

### ISSUE THREAD

**Issue by mengpengfei** [o2oa/o2oa#81]
![image](https://user-images.githubusercontent.com/13211758/89141214-79877880-d576-11ea-8e92-041d33828a01.png)
![image](https://user-images.githubusercontent.com/13211758/89141231-84420d80-d576-11ea-862b-0ae446d1148f.png)
商用得比这个体验好很多

**Comment by o2oa** [comment]
不同级别的东西没办法直接想比的：
您贴出来的是成熟的OA产品，但O2OA是一个低代码开发平台，可以开发OA类的应用，也可以开发其他类型的应用。在线体验效果作为开发平台，因为针对的使用者群体有较大的区别，所以的确普通用户在平台使用体验上没办法跟成品OA产品直接相比。
但是开发成OA系统就不一样的，哈哈！

<img width="800" alt="O2OA低代码开发平台" src="https://user-images.githubusercontent.com/25760764/89149451-135b1f80-d58f-11ea-9481-412daeeec3aa.png">

不管怎么样，O2OA会继续努力 ，继续加油！

**Comment by hefanbo** [comment]
所以呢？不指明具体问题，不提改进意见，不贡献代码，只会抱怨一个免费开源的东西不如商用产品，还是以你自己的标准判断。你开这个 Issue 有任何意义吗？

事实上，基于这个项目自己改几行代码，足够小型企业使用了。如果你觉得还不够好，请帮助改进它，而不是泛泛地攻击它。如果觉得该项目无药可救，欢迎你给开源社区贡献一个更好的项目，大家会表示感谢。如果连一个合格的 Issue 都提不出来，请保持沉默，还这里一片清净。

总之，请尊重开源文化，不要生产垃圾信息。

这个 Issue 对该项目没有任何贡献，建议管理员关掉。
