### ISSUE TITLE
整体代码是否全部开源

### ISSUE THREAD

**Issue by uzdz** [o2oa/o2oa#82]
开发者您好，请问o2oa的所有核心代码是否已经全部开源，例如oa流等？还有商用授权能给出一个页面吗，例如价格等报表。

**Comment by uzdz** [comment]
还有一个问题就是，后端服务没有使用其他中间件？例如activity工作流等？我是否可以理解o2oa的后端服务就是一个单体项目，启动运行即可，无其他中间件必装中间件。存储不算，默认不是h2么，这个我理解。

**Comment by o2oa** [comment]
1、核心代码全部开源，没有任何隐藏的部分，您可以放心使用
2、没有使用其他中间件，工作流自研
3、O2OA是一整套完整的服务，无须其他中间件，但是正式环境建议使用商用级数据库，H2性能太差，建议Mysql，Oracle或者其他国产数据库都行。
至于商用许可，您可以直接连接官网的客服，或者400电话，谢谢您的认可。

**Comment by uzdz** [comment]
好的，那么是不是不允许分布式部署呢？我没有看到移动端（ios/安卓）部署手册呢，请问如何查找或者您可以发给我吗？

最后一个问题，咱们o2oa项目是前后端分离的吗？是不是部署到服务器上，需要修改host端口等。

**Comment by o2oa** [comment]
1、允许分布式部署
2、移动端您可以下载源码进行编译，也可以直接扫描登录页上的二维码下载
3、O2OA是前后端分离的，所有的服务全部都是开放的。
4、是否需要修改端口，还需要看您的实际需求，默认需要80、20020、20030

https://www.yuque.com/o2oa/course/bfseq4

**Comment by uzdz** [comment]
1. 所谓支持分布式部署，也就是您自研的工作流是支持分布式部署的？这些技术有文档吗？
2. O2云是贵公司的公有服务器？无法私有化？O2云的存在是否就是为了移动端与我司私有化OA服务器的跳板中间层？

**Comment by o2oa** [comment]
1、所谓支持分布式部署，也就是您自研的工作流是支持分布式部署的？这些技术有文档吗？
回复：平台是分布式的，支持组件集群，可以将流程引擎进行集群试部署，可以将不同的组件进行分布式部署。
https://www.yuque.com/o2oa/course/dm9sor
这个文档比较老，不过可以参考一下。

2、O2云是贵公司的公有服务器？无法私有化？O2云的存在是否就是为了移动端与我司私有化OA服务器的跳板中间层？
回复：O2云不支持私有化部署，也不开源。O2云为了帮助用户自动绑定O2Server服务器，也可以理解为你说的跳板中间层，但是不是所有的请求都需要O2云，绑定服务器后，都是APP与服务器直接通信，不需要O2云。当然，您也可以修改APP源码，直接指定服务器地址来绕过O2云，技术支持服务可以支持您修改相应的源码。（注意：IOS源码编译打包，需要企业证书，需要您自己准备）
