### ISSUE TITLE
切换数据库为Kingbase8启动服务器druid报错

### ISSUE THREAD

**Issue by Eveink** [o2oa/o2oa#84]
`严重: merge sql error, dbType null, druid-1.1.21, sql : CREATE TABLE X.PP_C_READCOMPLETED( 
中略
) DEFERRABLE)
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'nce) DEFERRABLE)', expect RPAREN, actual IDENTIFIER pos 1998, line 1, column 1988, token IDENTIFIER DEFERRABLE`

经查是druid需要配置DataSource merge-sql为false，但是不知道在哪里添加配置。

**Comment by o2oa** [comment]
请检查 externalDataSources.json 文件是相关的配置：
[
	{
		"url" : "jdbc:kingbase://127.0.0.1:54321/X",
		"username" : "system",
		"password" :"krms",
		"includes": [],
		"excludes": [],
		"enable" : true,
		"logLevel": "TRACE",
		"statEnable": false,
		"statFilter" : false
	}
]
请添加两个属性：
"statEnable": false,
"statFilter" : false
然后再重启试试看。

谢谢对O2OA的支持。
