### ISSUE TITLE
神通数据库

### ISSUE THREAD

**Issue by sgaxun** [o2oa/o2oa#88]
请问神通数据库能用吗?我切换成神通数据库之后第一次启动项目插入数据时报错

`Caused by: <openjpa-3.1.0-rafcec21a1d489dff682a3ce7986fac6a1c80e8e0 fatal general error> org.apache.openjpa.persistence.PersistenceException: ERROR, 抽象数据类型错, TEXT 转目标类型1560失败
{prepstmnt 1060251152 INSERT INTO X.ATDC_ATTENDANCE_SETTING (xid, xcreateTime, xscratchBoolean, xscratchDate, xscratchInteger, xscratchString, xsequence, xupdateTime, xdistributeFactor, xconfigCode, xconfigName, xconfigValue, xdescription, xisMultiple, xorderNumber, xselectContent, xvalueType) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)} [code=0, state=40000]`

**Comment by zhouruicn** [comment]
这个bug是一个映射错误导致的,java中的boolean类型应该映射成神通数据库bool类型.
在新版本中已经修复.
	public OscarDictionary() {
		...
		doubleTypeName = "DOUBLE PRECISION";
		booleanTypeName = "BOOL";
	}

	protected BooleanRepresentation booleanRepresentation = BooleanRepresentationFactory.BOOLEAN;

**Comment by sgaxun** [comment]
感谢,已解决.
