### ISSUE TITLE
关于新功能建议

### ISSUE THREAD

**Issue by dilenzhu** [o2oa/o2oa#95]
1、如果UI能支持单页签或多页签会更能吸引人。
2、如果在线流程表单设计器支持Element-UI标签库，设计出来的表单会更精美一些(或者是能开放出来自定义html 编辑，虽说有标签支持)。
3、目前最不方便的还是调试(必须要远程调试或者是部署方式调试)。

**Comment by huqi1980** [comment]
目前正在开发新的表单组件设计器，不久以后就可以支持Element-UI在内的各种UI库。
O2OA的IDE开发工具也已经在计划中，相信会对开发调试，单元测试以及git集成的等各方面有大幅提升。

**Comment by dilenzhu** [comment]
感谢，因为我公司正在评估做O2OA代理！谢谢！
