### ISSUE TITLE
app端流程处理的时候，打开空白页面

### ISSUE THREAD

**Issue by WenSteven** [o2oa/o2oa#97]
在log中可以看出来要请求的页面地址是: `/x_desktop/workmobilewithaction.html?workcompletedid=aa0718fd-f19c-47eb-99f2-74d72164bb60&time=1615535122820`

不知道是编译的问题还是什么问题，或者这个是购买技术支持才可见 - -|

**Comment by o2oa** [comment]
我们所有的代码都开源的，所以不会有啥隐藏的收费功能。技术支持是你遇到问题需要我们帮助解决的时候提供的有偿服务！
你的这个问题，应该是没有配置对应的移动端表单页面导致的。你可以去看当前这个工作的节点在哪里，到对应的表单编辑器中查看下移动端的表单，并保存一下。

**Comment by WenSteven** [comment]
> 我们所有的代码都开源的，所以不会有啥隐藏的收费功能。技术支持是你遇到问题需要我们帮助解决的时候提供的有偿服务！
> 你的这个问题，应该是没有配置对应的移动端表单页面导致的。你可以去看当前这个工作的节点在哪里，到对应的表单编辑器中查看下移动端的表单，并保存一下。

非常感谢，是这个原因！
